AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Auto-Vid Serverless Video Processing Application

Globals:
  Function:
    Timeout: 900
    MemorySize: 3008
    Runtime: python3.12

Resources:
  AutoVidBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "auto-vid-${AWS::StackName}-${AWS::AccountId}"
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  AutoVidSharedLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub "auto-vid-shared-${AWS::StackName}-${AWS::AccountId}"
      ContentUri: layers/auto-vid-shared/
      CompatibleRuntimes:
        - python3.12
    Metadata:
      BuildMethod: python3.12

  SubmitJobFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/submit_job/
      Handler: app.lambda_handler
      Layers:
        - !Ref AutoVidSharedLayer
      Environment:
        Variables:
          AUTO_VID_BUCKET: !Ref AutoVidBucket
      Events:
        SubmitJob:
          Type: Api
          Properties:
            Path: /submit
            Method: post

  VideoProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      # PackageType: Image
      # ImageUri: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/auto-vid-processor:latest"
      CodeUri: src/
      Handler: video_processor.app.lambda_handler
      Timeout: 900
      MemorySize: 3008
      EphemeralStorage:
        Size: 10240
      Environment:
        Variables:
          AUTO_VID_BUCKET: !Ref AutoVidBucket
      Policies:
        - AmazonPollyFullAccess
        - S3CrudPolicy:
            BucketName: !Ref AutoVidBucket
      Events:
        ProcessJob:
          Type: SQS
          Properties:
            Queue: !GetAtt JobQueue.Arn

  GetStatusFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/get_status/
      Handler: app.lambda_handler
      Layers:
        - !Ref AutoVidSharedLayer
      Environment:
        Variables:
          AUTO_VID_BUCKET: !Ref AutoVidBucket
      Events:
        GetStatus:
          Type: Api
          Properties:
            Path: /status/{jobId}
            Method: get

  JobQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "auto-vid-jobs-${AWS::StackName}-${AWS::AccountId}"
      VisibilityTimeoutSeconds: 960

Outputs:
  SubmitJobApi:
    Description: "API Gateway endpoint URL for Submit Job function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/submit/"
  
  AutoVidBucket:
    Description: "S3 bucket for Auto-Vid assets and outputs"
    Value: !Ref AutoVidBucket
    Export:
      Name: !Sub "${AWS::StackName}-AutoVidBucket"
