AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Auto-Vid Serverless Video Processing Application

Resources:
  AutoVidBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "auto-vid-s3-bucket-${AWS::StackName}-${AWS::AccountId}"
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  AutoVidSharedLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub "auto-vid-layer-shared-${AWS::StackName}-${AWS::AccountId}"
      ContentUri: layers/auto-vid-shared/
      CompatibleRuntimes:
        - python3.12
    Metadata:
      BuildMethod: python3.12

  JobStatusTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "auto-vid-dynamodb-jobs-${AWS::StackName}-${AWS::AccountId}"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: jobId
          AttributeType: S
      KeySchema:
        - AttributeName: jobId
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  SubmitJobFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/submit_job/
      Handler: app.lambda_handler
      Runtime: python3.12
      MemorySize: 512
      Timeout: 60
      Layers:
        - !Ref AutoVidSharedLayer
      Environment:
        Variables:
          JOB_QUEUE_URL: !Ref JobQueue
          JOB_STATUS_TABLE: !Ref JobStatusTable
          DYNAMODB_JOB_TTL_SECONDS: 604800
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt JobQueue.QueueName
        - DynamoDBCrudPolicy:
            TableName: !Ref JobStatusTable
      Events:
        SubmitJob:
          Type: Api
          Properties:
            Path: /submit
            Method: post

  videoprocessorfunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Timeout: 900
      MemorySize: 10240
      EphemeralStorage:
        Size: 10240
      Environment:
        Variables:
          AUTO_VID_BUCKET: !Ref AutoVidBucket
          AWS_REGION: !Ref AWS::Region
          JOB_STATUS_TABLE: !Ref JobStatusTable
          DYNAMODB_JOB_TTL_SECONDS: 604800
          WEBHOOK_MAX_HEADERS_SIZE: 1024
          WEBHOOK_MAX_METADATA_SIZE: 1024
          S3_PRESIGNED_URL_EXPIRATION: 86400
      Policies:
        - AmazonPollyFullAccess
        - S3CrudPolicy:
            BucketName: !Ref AutoVidBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref JobStatusTable
      Events:
        ProcessJob:
          Type: SQS
          Properties:
            Queue: !GetAtt JobQueue.Arn
    Metadata:
      Dockerfile: Dockerfile.videoprocessor
      DockerContext: .
      DockerTag: latest

  GetStatusFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/get_status/
      Handler: app.lambda_handler
      Runtime: python3.12
      MemorySize: 256
      Timeout: 30
      Layers:
        - !Ref AutoVidSharedLayer
      Environment:
        Variables:
          JOB_STATUS_TABLE: !Ref JobStatusTable
          DYNAMODB_JOB_TTL_SECONDS: 604800
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref JobStatusTable
      Events:
        GetStatus:
          Type: Api
          Properties:
            Path: /status/{jobId}
            Method: get

  JobQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "auto-vid-sqs-jobs-${AWS::StackName}-${AWS::AccountId}"
      VisibilityTimeout: 960

Outputs:
  SubmitJobApi:
    Description: "API Gateway endpoint URL for Submit Job function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/submit/"

  GetStatusApi:
    Description: "API Gateway endpoint URL for Get Status function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/status/"

  AutoVidBucket:
    Description: "S3 bucket for Auto-Vid assets and outputs"
    Value: !Ref AutoVidBucket
    Export:
      Name: !Sub "${AWS::StackName}-AutoVidBucket"

  JobStatusTable:
    Description: "DynamoDB table for job status tracking"
    Value: !Ref JobStatusTable
    Export:
      Name: !Sub "${AWS::StackName}-JobStatusTable"

  JobQueue:
    Description: "SQS queue for video processing jobs"
    Value: !Ref JobQueue
    Export:
      Name: !Sub "${AWS::StackName}-JobQueue"
